### PR TITLE
Make a variety of formatting changes in contrib/cloud9

### PR DESCRIPTION
**Pull request by zachlatta**
This PR makes a variety of formatting changes in @Bogidon's contributed Cloud9 workshop.

@Bogidon can you review and merge this when you have the opportunity?

### CODE REVIEW

**Comment by paked** [comment]
@zachlatta this PR needs to be cleaned up

**Comment by Bogidon** [comment]
Hey @zachlatta sorry I haven't responded yet. Will check and merge tomorrow.

**Comment by paked** [comment]
[URGENT] @zachlatta @MaxWofford this PR is git hell. It needs to be cleaned before @Bogidon merges!

**Comment by jonleung** [comment]
^ agreed with @Bogidon. Assigning this to @zachlatta.

**Comment by zachlatta** [comment]
Git hell=resolved.

@Bogidon you should be good to go!

**Comment by Bogidon** [comment]
Thanks guys. Sorry for leaving this unattended.

**Comment by hellyeah** [comment]
This branch is out-of-date. Do I need to pull it down, pull, rebase, push then merge?

**Pull request merged**
