### PR TITLE
Add Club Faire Notes from Sept

### PR DESCRIPTION
**Pull request by ssun098**

### CODE REVIEW

**Comment by MaxWofford** [comment]
This looks like a duplicate of https://github.com/hackedu/hackedu/pull/341/files. Did you mean to push something else to this branch?

**Comment by ssun098** [comment]
Wait this isn't right

**Comment by ssun098** [comment]
@MaxWofford it should be fixed now, sorry about that! I was in the wrong dir

**Comment by MaxWofford** [comment]
Moved to https://github.com/hackedu/hackedu/pull/344

**Pull request closed without merging**
