### PR TITLE
Describe purpose of playbook/workshops/contrib

### PR DESCRIPTION
**Pull request by zachlatta**
Per #262. This certainly isn't the best description, but I figure it's a start and can be improved in future pull requests.

@paked can you take a look at this and merge when you have a chance?

### CODE REVIEW

**Comment by paked** [comment]
@zachlatta feedback given

**Comment by zachlatta** [comment]
Just changed `User-contributed` to `Unofficial`. Let me know if it's ready for merge and I'll squash the commits.

**Comment by paked** [comment]
@zachlatta yep. LGTM. squash 'em!

**Comment by zachlatta** [comment]
They done been squashed. Go for it!

**Comment by paked** [comment]
@zachlatta this is now out of date with master :cry:

**Comment by zachlatta** [comment]
Rebased my changes on top of master!

**Comment by paked** [comment]
Merged.

**Pull request merged**
