### PR TITLE
Dodge refactor

### LINKED ISSUE #360: Dodge Workshop is Currently Too Hard To Play
Make the bullet slower. It's too hard to ~~win~~ stay alive right now.

### PR DESCRIPTION
**Pull request by jonleung**
@j1lin0101 had an issue at his club where Imgur was blocked at his school. This makes a fix that removes all traces of imgur in the code and the JS Bins.

At the same time, this also fixes #360 by making the demo game easier to play

@paked, do you have bandwidth to review this?

It would be helpful to check

- [x] all the navigation works between parts of the tutorial
- [x] all JS Bins are properly linked and have the proper code

@j1lin0101, please comment here if you experience any errors in this version of workshop!

### CODE REVIEW

**Comment by paked** [comment]
@jonleung challenge accepted.

**Comment by jonleung** [comment]
Thanks @paked!

**Comment by paked** [comment]
@jonleung Did we decide the final movement speed should be `18px`? Do we want this reflected in the gifs too?

**Comment by paked** [comment]
@jonleung ping ping

**Comment by jonleung** [comment]
@paked, the speed is whatever it is in the demo at the top of the readmd. ideally reflected in the gifs but I think there are bigger fish to fry. I'll let you call it.

**Comment by paked** [comment]
@jonleung I just can't tell if you actually changed it... Damn placebo!

**Comment by paked** [comment]
@jonleung It appears you did, but not in the screenshots?

**Comment by jonleung** [comment]
@paked I thought I did... Check the diff for the links to the JS Bins and compare what the values are?  Sorry I'm currently on mobile right now.

**Comment by paked** [comment]
@jonleung everything seems to be at `18px`. This is what is reflected in the screenshots and JSBins, however it is the same as the repo in the master branch. So it doesn't seem any change to difficulty has been made?

**Comment by jonleung** [comment]
@paked so when you look at this diff:

https://github.com/hackedu/hackedu/commit/79efdd53d2373276742d63bc6aacadcc2d363de0#diff-daa448c1e08ef71a10c673531f320ae0R5

It changes the [old JS Bin](http://jsbin.com/dozoki/63/edit?js,output) to this new [JS Bin](http://jsbin.com/dozoki/70/edit?js,output) effectively changing the speed to 13 pixels per frame.

**Comment by paked** [comment]
@jonleung Ah ok. My bad. LGTM.

**Comment by jonleung** [comment]
@paked feel free to rebase and merge : )

**Comment by paked** [comment]
DERP

**Comment by paked** [comment]
KA POW

Thanks for the contribution @jonleung ;)

**Pull request merged**
