### PR TITLE
Schedule all interviews 

### LINKED ISSUE #54: Introduce all club leaders to Dave for interviews
Spreadsheet linked in https://github.com/hackedu/hackedu/tree/master/meta/labs_program.

/cc @jonleung @hellyeah

### PR DESCRIPTION
**Pull request by zachlatta**
@hellyeah can you review/merge this when you have the opportunity? This closes #54.

/cc @jonleung

### CODE REVIEW

**Comment by hellyeah** [comment]
We have 6/27 interviews waiting to be scheduled. I will follow-up and aim to have them all scheduled by the end of the weekend.

List of club leaders without scheduled interviews:
1. Pasadena
2. Grace Zhang
3. All Star Code
4. Abby Med
5. Yashwee
6. Alexis

**Comment by zachlatta** [comment]
@hellyeah update on this?

**Comment by zachlatta** [comment]
Status on this?

On Fri, Aug 21, 2015 at 6:16 PM, David Fontenot <notifications@github.com>
wrote:

> We have 6/27 interviews waiting to be scheduled. I will follow-up and aim
> to have them all scheduled by the end of the weekend.
>
> List of club leaders without scheduled interviews:
> 1. Pasadena
> 2. Grace Zhang
> 3. All Star Code
> 4. Abby Med
> 5. Yashwee
> 6. Alexis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/75#issuecomment-133622867>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
#75 replaced this.

**Comment by zachlatta** [comment]
Huh, this should actually be merged...

**Comment by hellyeah** [comment]
All interviews have been scheduled and have taken place.

**Pull request merged**
