### PR TITLE
9 3 15 san leandro club fair and 9 10 15 san leandro first meeting

### PR DESCRIPTION
**Pull request by xeonjake**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@xeonjake Would you like this reviewed and merged?

**Comment by zachlatta** [comment]
Whoops, accidentally assigned myself!

**Comment by xeonjake** [comment]
@MaxWofford yeah

**Comment by MaxWofford** [comment]
I've rebase this and put it in #206

**Comment by zachlatta** [comment]
:tada: :tada: :tada: 

giphy

Thank you for contributing @xeonjake!

**Pull request closed without merging**
