### PR TITLE
9/26 SMHS 9th Meet

### PR DESCRIPTION
**Pull request by saescapa**

### CODE REVIEW

**Comment by saescapa** [comment]
Fixing issues rn.

**Comment by paked** [comment]
@saescapa have you finished applying fixes here? I'm happy to clean this up and merge it in?

**Comment by saescapa** [comment]
Don't worry I got it, it's just a small typo. Thank you tho @paked . Sorry for all of these wrong commits. Was doing some mistakes again.

**Comment by saescapa** [comment]
@jonl If you want to view my files, here they are.

**Comment by zachlatta** [comment]
@saescapa perhaps you meant to mention @jonleung?

**Comment by saescapa** [comment]
@zachlatta Yeah Thank you, @jonleung You can experiment with these if you want. I would gladly help.

**Comment by jonleung** [comment]
Awesome, thanks @saescapa! @MaxWofford can you help merge these in?

**Comment by MaxWofford** [comment]
@jonleung I'm currently doing stuff with markcop and won't be able to do this in a timely manner. You should be able to just rebase, squash, and merge.

**Comment by MaxWofford** [comment]
@saescapa Thanks for the contribution!



@jonleung I'm working with MarkCop, and won't be able to merge in a timely manner.

**Pull request merged**
