### PR TITLE
Xeonjake's October 15th meeting (Merging #369)

### PR DESCRIPTION
**Pull request by paked**
This is the reformatted version of @xeonjake's PR.

cc: @MaxWofford

### CODE REVIEW

**Comment by MaxWofford** [comment]
@paked Would you please update this with master?

**Comment by paked** [comment]
@MaxWofford done.

**Comment by MaxWofford** [comment]
@paked It would also be awesome if you could rename and/or squash the commits. `Create Planning.md` should be replaced with a club-specific title; ex. `San Leandro 4th meeting case study`

**Comment by paked** [comment]
@MaxWofford done.

**Pull request merged**
