### PR TITLE
shorten tag-line

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
This addresses issue#59

**Comment by zachlatta** [comment]
You can just say #59, it'll link it then.

**Comment by MaxWofford** [comment]
Just cleaned up this commit-- it should be ready for review now.

**Comment by zachlatta** [comment]
Can you merge master into this? Can't automatically merge.

**Comment by MaxWofford** [comment]
@zachlatta

**Comment by zachlatta** [comment]
Awesome! :shipit:

Can you squash all the commits before merge?

**Comment by MaxWofford** [comment]
Woah O_O
I never knew I could do such magical things with git as I have just done. It was like looking into an abyss of all of history being bundled into commits and rebasing branches of it tangling and breaking off before settling on the head commits of other branches. I see now that I must learn much more to ultimately defeat the enemy.

**Comment by MaxWofford** [comment]
But... yea, it's ready for a merge @zachlatta

**Comment by zachlatta** [comment]
Merged and deployed!

**Pull request merged**
