### PR TITLE
added markdown file to curate sweet resources

### PR DESCRIPTION
**Pull request by JevinSidhu**
Created RESOURCES.md and add a Code Guide by [@mdo](https://twitter.com/mdo)

### CODE REVIEW

**Comment by paked** [comment]
@MaxWofford Is it possible to get this merged soon? I have a few resources I'd like to add!

**Comment by MaxWofford** [comment]
This looks awesome! I'll get right on it if @JevinSidhu is  okay with me merging it.

**Comment by JevinSidhu** [comment]
@MaxWofford Yup, merge it! :)

**Comment by MaxWofford** [comment]
Just moved to https://github.com/hackedu/hackedu/pull/451

**Pull request closed without merging**
