### PR TITLE
fix issue#39, README mentions grasp

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
Could someone merge this? @zachlatta

**Comment by zachlatta** [comment]
Can you reflow the text so it's using the full 80 characters on the line?

**Comment by zachlatta** [comment]
Awesome! Can you squash these commits before merging?

See https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by MaxWofford** [comment]
@zachlatta

**Pull request merged**
