### PR TITLE
Add planning.md & recap.md to first meeting in LAHS folder, but new branch

### PR DESCRIPTION
**Pull request by ssun098**
Made new branch for commits because the old one seems dangerous

### CODE REVIEW

**Comment by ssun098** [comment]
Oh dear I'm not sure if all the commits were supposed to be included...

**Comment by paked** [comment]
ugh. it looks like my plan failed. I swear that worked for me... What happens if you force push the old branch? @ssun098

**Comment by ssun098** [comment]
Uhh do you have the line for that? I know I'm going to screw something up

**Comment by paked** [comment]
@ssun098 `git push -f`

**Comment by ssun098** [comment]
....I'm not sure what to do with this
image

**Comment by paked** [comment]
@ssun098 just copy out the last line :)

**Comment by ssun098** [comment]
@paked lol it got rejected gg

**Comment by paked** [comment]
@ssun098 did you `-f` it?

**Comment by ssun098** [comment]
@paked uhh was i supposed to `git push -f --set-upstream origin add-lahs-notes`
because i only ran `git push --set-etc...`

I also got a merge conflict and that probably isn't good 

image

**Comment by paked** [comment]
@ssun098 yeah. You got merge conflicts because you didn't force it. Git is now trying to merge all the changes which were reverted with that script that was run earlier today... See if you can exit the merge process. `git status` usually has some info on that.

**Comment by ssun098** [comment]
I wqed out of the merge conflict. . .  
I force pushed in #301 but i'm not sure if it's actually legit

**Comment by MaxWofford** [comment]
Cherry-picked into master on 7c4e59b2c27c1cf1407d0e8c60653df91ce4d0d2

**Comment by ssun098** [comment]
Thanks @maxwofford!

**Pull request closed without merging**
