### PR TITLE
aesthetic changes for email subscription form

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
This _probably_ is too small to break anything.

**Comment by zachlatta** [comment]
that's what tests are for :D

**Comment by MaxWofford** [comment]
[Well, let's do some tests and see what happens](http://i1.theportalwiki.net/img/6/62/GLaDOS_botcoop_artifactone_hub08.wav)

**Comment by zachlatta** [comment]
tmp

**Comment by zachlatta** [comment]
tmp

**Comment by zachlatta** [comment]
max we should make a chrome extension that lets you search for gifs while commenting on github issues/pull requests. kinda like how you can start typing `:+` and you'll see a suggestion.

**Comment by MaxWofford** [comment]
This must become a thing! We could hook up steward to github. He could comment on all the commits as they happen.
screenshot 2015-03-19 at 2 48 27 am

**Comment by zachlatta** [comment]
what do you mean by comment on all the commits as they happen?

**Pull request merged**
