### PR TITLE
Clarify that users should work on workshops independently

### PR DESCRIPTION
**Pull request by Cydrobolt**
This was originally unclear to me, but it makes a lot of sense when it is clarified. Having people listening a single person present a workshop is difficult and not manageable with many people.

### CODE REVIEW

**Comment by paked** [comment]
@Cydrobolt You should rebase this to squash those excess commits!

**Comment by Cydrobolt** [comment]
Do we want to rebase it? I don't think 2 commits is really worth rebasing

**Comment by paked** [comment]
@Cydrobolt Unfortunately we haven't gotten these sorts of guidelines into the `CONTRIBUTING.md` yet. However, we would like to start ensuring that each commit is a single logical unit of work. While these aren't in the repository yet, something will be soon.

**Comment by Cydrobolt** [comment]
I generally don't let rewriting history, such as what would happen if I rebased those commits then force-pushed them to my branch. However, I'll rebase them since it looks like you prefer this kind of workflow.

**Comment by paked** [comment]
@Cydrobolt I'll take these thoughts into consideration next time we have a discussion on the guidelines. 

Thanks for your contribution!

**Pull request merged**
