### PR TITLE
Fix typos and consistency of layout in Workshops

### PR DESCRIPTION
**Pull request by klipspringr**

### CODE REVIEW

**Comment by klipspringr** [comment]
Forgot to add: In Frogger section, "Learn to build frogger.", Frogger in this sentence should be capitalized.

**Comment by MaxWofford** [comment]
@klipspringr I'd be happy to merge after you add the Frogger fix.

**Comment by klipspringr** [comment]
pull requests are hard. did I edit it correctly?

**Comment by MaxWofford** [comment]
@klipspringr Awesome! You did it correctly. Would you please squash these commits?

**Comment by klipspringr** [comment]
I'm just working in my browser

**Comment by MaxWofford** [comment]
@klipspringr Ah, Okay. I'll squash it then!

**Comment by MaxWofford** [comment]
@klipspringr I'll squash this with https://github.com/hackedu/hackedu/pull/400 in that case.

**Comment by MaxWofford** [comment]
This is part of https://github.com/hackedu/hackedu/pull/402

**Pull request closed without merging**
