### PR TITLE
october 15th meeting

### PR DESCRIPTION
**Pull request by xeonjake**

### CODE REVIEW

**Comment by paked** [comment]
Hey @xeonjake it looks like you have some markdown errors – Specifically, you are not wrapping each line to 80 characters.

**Comment by jonleung** [comment]
@paked for future reference, we are opting to fix markdown errors ourselves so that we do not burden club leaders with having to "deal" with fixing minor syntax things.

**Comment by paked** [comment]
@jonleung Yup. I ended up doing that with #370.

Have we got that information in a guideline somewhere?

**Comment by paked** [comment]
Closing in favour of #370.

**Pull request closed without merging**
