### PR TITLE
Change link from freenode webchat to kiwiirc

### PR DESCRIPTION
**Pull request by ZucchiniZe**
Kiwiirc has a better interface than webchat.freenode.com

### CODE REVIEW

**Comment by zachlatta** [comment]
Awesome contribution, thank you!

**Comment by ZucchiniZe** [comment]
does that say adorbes?

**Comment by zachlatta** [comment]
Indeed it does.

Can you also submit a PR to [hackedu/website](https://github.com/hackedu/website) to change the link to IRC in the footer?

**Comment by zachlatta** [comment]
Link to line to change: https://github.com/hackedu/website/blob/master/app/views/pages/home.html.haml#L175

**Comment by ZucchiniZe** [comment]
already an issue for it but will make a pr for it anyways https://github.com/hackedu/website/issues/164#issuecomment-142659970

**Comment by zachlatta** [comment]
Ah, that's for embedding the IRC client in an iframe on the site. Can you just change the existing link in the footer to use KiwiIRC?

**Comment by ZucchiniZe** [comment]
done hackedu/website#172

**Pull request merged**
