### PR TITLE
Move workshops to root of repository

### LINKED ISSUE #268: Page we can send people when they ask for the curriculum
A common occurrence on IRC is for an outsider to pop by and ask:

> 00:00:00 – some_new_user – Where can I find the curriculum?

At the moment whoever is online at the time will usually reply with a link to http://github.com/hackedu/hackedu/blob/master/playbook/workshops... And then, upon realising that there is only one workshop begin linking to hackedu/hack-camp and various PRs lying around the place. It would be much more effective to have all these resources bundled together along with an explanation as to *why* it is arranged like this.

`ZucchiniZe` on IRC proposed setting up steward to have factoid support. However, I believe it should be ingrained in the actual repository.

> Factoid: an item of unreliable information that is reported and repeated so often that it becomes accepted as fact.

### PR DESCRIPTION
**Pull request by zachlatta**
Closes #268.

### CODE REVIEW

**Comment by jonleung** [comment]
@zachlatta, why is there a workshops folder inside of the workshops folder?

image

**Comment by zachlatta** [comment]
@jonleung good catch! Just updated the PR and fixed that.

**Comment by jonleung** [comment]
@zachlatta these two links are still broken:

image

**Comment by zachlatta** [comment]
Another good catch! Fixed that as well.

**Pull request merged**
