### PR TITLE
SMHS 11th meet

### PR DESCRIPTION
**Pull request by saescapa**
Along with 8th Grade Night, 10th Meet, 11th Meet (cancelled). HackingEDU will be done along with 11th Meet tomorrow.

### CODE REVIEW

**Comment by saescapa** [comment]
@MaxWofford I got this error: 
"workshops/how_to_make_a_workshop/README.md:30 is missing a newline before or after the heading!
workshops/workshop_details.md:53 is missing a newline before or after the heading!"

I didn't edit those at all.

**Comment by MaxWofford** [comment]
@saescapa You got it! Just pull --rebase from master and it should be good to go.

**Comment by saescapa** [comment]
@MaxWofford I get this error after I run git pull --rebase upstream master from master and also from my branch.

```fatal: SMHS-10th-meet cannot be resolved to branch.```

**Comment by MaxWofford** [comment]
@saescapa What does this print?

```
git remote -v && git status
```

**Comment by saescapa** [comment]
@MaxWofford 

```
origin	https://github.com/saescapa/hackedu/ (fetch)
origin	https://github.com/saescapa/hackedu/ (push)
upstream	https://github.com/hackedu/hackedu (fetch)
upstream	https://github.com/hackedu/hackedu (push)
On branch SMHS-10th-Meet
nothing to commit, working directory clean
```

**Comment by MaxWofford** [comment]
@saescapa Try this

`git pull --rebase upstream master`

`git push upstream SMHS-10th-Meet`

**Comment by saescapa** [comment]
@MaxWofford Error:

```
remote: Permission to hackedu/hackedu.git denied to saescapa.
fatal: unable to access 'https://github.com/hackedu/hackedu/': The requested URL returned error: 403
```

**Comment by MaxWofford** [comment]
@saescapa Sorry, I screwed that up
```
git pull --rebase upstream master

git push origin SMHS-10th-Meet
```

**Comment by saescapa** [comment]
@MaxWofford Error:

```
To https://github.com/saescapa/hackedu/
 ! [rejected]        SMHS-10th-Meet -> SMHS-10th-Meet (non-fast-forward)
error: failed to push some refs to 'https://github.com/saescapa/hackedu/'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by MaxWofford** [comment]
@saescapa You'll need to force push after rebasing

`git push -f origin SMHS-10th-Meet`

**Comment by saescapa** [comment]
@MaxWofford Thank you so much! Everything solved, should be working!

**Comment by MaxWofford** [comment]
@saescapa Thanks for contributing!

**Pull request merged**
