### PR TITLE
add 15-08-15 meeting notes

### PR DESCRIPTION
**Pull request by jonleung**

### CODE REVIEW

**Comment by zachlatta** [comment]
Was I also in this meeting?

**Comment by jonleung** [comment]
@zachlatta, you were not

**Comment by jonleung** [comment]
pinging @zachlatta  ^_^

**Comment by zachlatta** [comment]
Can you link this in the Labs README? It's in `meta/labs/README.md`

**Comment by jonleung** [comment]
@zachlatta I just linked it. Thanks!

**Comment by jonleung** [comment]
Assigning this to @MaxWofford!

**Comment by MaxWofford** [comment]
@jonleung Thanks for assigning me! It's good for keeping tabs on everything.

**Pull request merged**
