### PR TITLE
recap on the first club meeting at RHS

### PR DESCRIPTION
**Pull request by tejasmanohar**

### CODE REVIEW

**Comment by tejasmanohar** [comment]
@MaxWofford 

Saw the 80 char rule in Style Guide

I use word wrapping in my editor so I guess I don't really notice how long these lines are. Do you recommend I just split lines on punctuation that ends sentences (and maybe commas for longer sentences)?

**Comment by MaxWofford** [comment]
@tejasmanohar What editor do you use? There may be a way to temporarily get around word wrapping.

**Comment by tejasmanohar** [comment]
@MaxWofford ST3. pretty sure i can setup file type-specific preferences.

**Comment by tejasmanohar** [comment]
@MaxWofford I just setup a ruler at 80 chars and then split the lines. easier, i like word wrapping :)

**Comment by zachlatta** [comment]
Squashed and cherry picked into master in 65edb7c5568c7c79914ddb6e99c50cd97df36c63. Thank you!

**Comment by tejasmanohar** [comment]
Thanks!

**Pull request closed without merging**
