### PR TITLE
fix inline text on sponsor page

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta For review purposes, is it better to make a .header class that can be applied to spans, or a .inline class that can be applied to headers?

**Comment by zachlatta** [comment]
Hmm, that's a good question. I'm not too familiar with best practices for CSS, but `.inline` for headers sounds more intuitive because all of the different header classes already exist. I'd try asking in the #css channel on Freenode.

**Comment by MaxWofford** [comment]
Haml derps when headers are nested in `p` tags. I'll look into this, but I think from a haml perspective it would be better to leave it the way it is, or go to html.

**Comment by MaxWofford** [comment]
This may be a haml gem bug; https://haml2erb.org/ converts it correctly

**Comment by MaxWofford** [comment]
My vote is for merging this for now and submitting another PR for switching from .header class to .inline class.

**Comment by zachlatta** [comment]
👍 you have the go ahead to merge, can't do it from mobile atm.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Pull request merged**
