### PR TITLE
Add notes from LA clubs meeting to Labs

### PR DESCRIPTION
**Pull request by zachlatta**
@jonleung can you review/merge this when you have a chance?

/cc @hellyeah @gemmabusoni @jonleung

### CODE REVIEW

**Comment by jonleung** [comment]
@zachlatta, it seems like the changes in this PR do not reflect what is in the [original meeting notes](http://thinfi.com/pa3). Is that intentional? Note that the password for the shortened URL is our standard password for unsecure things).

Also, I personally find being able to see `TODO` in our meeting notes to be helpful. Thoughts on leaving them in there?

**Comment by zachlatta** [comment]
The only change I believe I made was removing the TODO items (and including them in issues that link this pull request).

Do you see other changes?

--
Zach Latta
hackEDU| zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, I think it is important to include all the actionables decided on in a meeting in the meeting notes.

For example, I think `Set time to talk with Gemma about weeks for her to come up` should be documented in the meeting notes.

**Comment by zachlatta** [comment]
Added actionables to the notes!

**Comment by jonleung** [comment]
:+1:

**Pull request merged**
