### PR TITLE
Reword branch instructions to clarify feature branches

### PR DESCRIPTION
**Pull request by paked**
We are beginning to use this terminology in a few different places. But AFAIK we are never actually defining it...

### CODE REVIEW

**Comment by MaxWofford** [comment]
@paked Thanks! Would you please wrap that at 80 chars?

**Comment by paked** [comment]
Done @maxw

**Comment by maxw** [comment]
Will you do me a favor and have Max change his irc username so I stop
getting pinged about this project?

Max

**Comment by paked** [comment]
sorry @maxw :(

**Comment by MaxWofford** [comment]
@maxw So sorry! Looking into changing it right now.

**Comment by MaxWofford** [comment]
@paked It looks like a few extra things got word-wrapped (including a table). Would you please amend the commit with just a fix for line 145?

**Comment by paked** [comment]
@hackedu/core *testing testing 123*

**Comment by paked** [comment]
Fixed.

**Comment by MaxWofford** [comment]
Thanks @paked!

**Pull request merged**
