### PR TITLE
Create labs followup 

### PR DESCRIPTION
**Pull request by hellyeah**
PR for #62

### CODE REVIEW

**Comment by zachlatta** [comment]
Can you make this a Markdown file?

Also: we generally use `_` as a space substitute in filenames (branches tend to be `-`).

**Comment by hellyeah** [comment]
Changed to underscores. @zachlatta can you reiterate the naming conventions that are standard? I should know these.

**Comment by zachlatta** [comment]
- All lowercase
- Instead of spaces use:
  - `-` as space separator for branch names.
  - `_` as space separator for file names.

I've opened #105 to add this to `CONTRIBUTING.md`.

On Wed, Aug 26, 2015 at 12:57 PM, David Fontenot <notifications@github.com>
wrote:

> Changed to underscores. @zachlatta <https://github.com/zachlatta> can you
> reiterate the naming conventions that are standard? I should know these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/81#issuecomment-135154215>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Anything that I need to do before we can merge and close this?

**Comment by zachlatta** [comment]
Squashed and cherry-picked into master in 63f708a.

**Comment by zachlatta** [comment]
Nope! Took care of it.

On Thu, Aug 27, 2015 at 11:04 AM, David Fontenot <notifications@github.com>
wrote:

> Anything that I need to do before we can merge and close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/81#issuecomment-135508876>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Pull request closed without merging**
