### PR TITLE
Fix typos in Soccer (Add Player Step)

### PR DESCRIPTION
**Pull request by klipspringr**

### CODE REVIEW

**Comment by klipspringr** [comment]
Not sure how to squash these commits.... :(

**Comment by paked** [comment]
Closed in favour of #413

**Comment by jonleung** [comment]
@klipspringr SOOOO MUCH LOOOOVE! THAAAAAAAANKS!

**Comment by paked** [comment]
@jonleung @klipspringr is literally OP. :heart:

**Pull request closed without merging**
