### PR TITLE
Add Los Altos Case Study folder

### PR DESCRIPTION
**Pull request by ssun098**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@ssun098 Just a heads up, when you pull if you add the `--rebase` flag, it will pull without making merge commits such as 16a06e3578c78d5332d8cf59f9dfae547829e4cf
screenshot from 2015-09-27 16 39 34

**Comment by ssun098** [comment]
@MaxWofford so `git pull https://github.com/hackedu/hackedu --rebase` ?
I just want to be sure because I've had VERY bad experiences with rebase

**Comment by MaxWofford** [comment]
@ssun098 `git pull https://github.com/hackedu/hackedu master --rebase`

Also, make sure to use [feature-branches](https://github.com/hackedu/hackedu/blob/master/CONTRIBUTING.md#case-study-contribution-walkthrough). If I cherry pick this into hackedu/hackedu's `master` and change something in the commit, your `master` will break.

**Comment by ssun098** [comment]
@MaxWofford This command would be run after forking, right?
@zachlatta  mentioned feature branches to me, but he said I could leave this PR the way it is, then refork/new branch after it gets cherry picked.

**Comment by MaxWofford** [comment]
@ssun098 Ah, sounds good! If you are reforking everything is fine.

**Comment by MaxWofford** [comment]
@ssun098 Cherry picked into master on https://github.com/hackedu/hackedu/commit/c73faae336955724655004336f823c6bc743a604 & https://github.com/hackedu/hackedu/commit/71d49cb0d3657b3144f07e1be8a86be827ed8443

Thanks for the contribution!

**Pull request closed without merging**
