### PR TITLE
Add club fair information to glenaeon

### PR DESCRIPTION
**Pull request by paked**

### CODE REVIEW

**Comment by paked** [comment]
@zachlatta it looks like the commit isn't being sunk with my github account? Is that normal?

**Comment by zachlatta** [comment]
Hmm, that's interesting. I assume `user.email` isn't set in the global git settings.

We'll have to add a section to `CONTRIBUTING.md` on having people do that when submitting case studies.

**Comment by paked** [comment]
TBH it sounds like something cloud9 should implement...

**Comment by paked** [comment]
@zachlatta I'll have another crack at this later on. If it is reproducible (I am convinced it is a bug) I will submit a PR to `CONTRIBUTING.md` with a fix.

**Comment by paked** [comment]
I've replaced this with #181.

**Pull request closed without merging**
