### PR TITLE
Add rafej to Cohort 1

### PR DESCRIPTION
**Pull request by rafej**

### CODE REVIEW

**Comment by paked** [comment]
@zachlatta do you want me to walk @rafej through fixing mege conflicts?

**Comment by zachlatta** [comment]
That would be awesome! Especially if you resolve it by rebasing, so there's
no extra commits.

On Monday, August 31, 2015, Harrison Shoebridge <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> do you want me to walk @rafej
> <https://github.com/rafej> through fixing mege conflicts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/139#issuecomment-136547926>.
>


-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by paked** [comment]
Sure @zachlatta we will do that now.

**Comment by paked** [comment]
whoops that isn't good

**Comment by paked** [comment]
@rafej will fix this over hangouts sometime tongiht

**Comment by zachlatta** [comment]
Sounds good!

On Mon, Aug 31, 2015 at 9:10 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> @rafej <https://github.com/rafej> will fix this over hangouts sometime
> tongiht
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/139#issuecomment-136578565>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
#143 replaced this.

**Pull request closed without merging**
