### PR TITLE
add email subscription section to homepage

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
The button's blue mouse-over should be changed to something that fits it's orange background.

**Comment by MaxWofford** [comment]
I just styled the submission button to fit the look of the page. It will be animated sometime tomorrow.

**Comment by zachlatta** [comment]
Let me know when you're ready for me to review functionality/code.

**Comment by MaxWofford** [comment]
Hover animations aren't working yet on the input button. I'm reading through hover.css to fix this. Everything else is ready for inspection.

**Comment by zachlatta** [comment]
All looks well. Let me know once you've added the hover animations.

**Comment by MaxWofford** [comment]
Let's launch this for now and add the hover animations as another issue. I don't want to hold up this PR   by playing with css for a long time.

**Comment by zachlatta** [comment]
You shouldn't have to play with CSS to get this working. Isn't it just adding a class to the button like we have for the call to action on the homepage?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Hover.css classes aren't working on submit input tags.

**Comment by zachlatta** [comment]
Gonna go ahead and merge this--not sure if it actually makes sense to have an animation on hover for the button.

**Pull request merged**
