### PR TITLE
Add sponsor list

### PR DESCRIPTION
**Pull request by MaxWofford**
This PR is made to fix issue#53.

### CODE REVIEW

**Comment by MaxWofford** [comment]
Don't merge yet- this PR has yet to be tested on mobile.

**Comment by MaxWofford** [comment]
How about we merge this for the time being, and I'll keep updating it with new logos. Thoughts @zachlatta?

**Comment by zachlatta** [comment]
This won't work with the Rails asset pipeline because you're giving the `img` tag an absolute path to the image file instead of using Rails's helper that'll use the correct path with the compiled assets. I'm fixing that now.

**Comment by zachlatta** [comment]
Summary of my changes:

* Use `image_tag` helper from Rails to accommodate for the asset pipeline
* Use Foundation's [block grid](http://foundation.zurb.com/docs/components/block_grid.html) to nicely reflow images instead of having to do it manually.

I'm gonna go ahead and squash the commits and merge.

**Comment by zachlatta** [comment]
I take that back. I'm afraid to squash the commits, just gonna merge.

**Pull request merged**
