### PR TITLE
Finish making list of leaders to interview

### LINKED ISSUE #30: Make list of clubs/leaders to interview.
One of the things not mentioned in our https://github.com/hackedu/hackedu/blob/71508adc8c092b2c1059cfa88b04537197a54635/meta/labs_program/meetings/15-07-13_initial_brainstorm.md discussion, but that we'll need to do is actually selecting the 12 clubs to partake in our labs program going into next semester. Any thoughts on selection criteria?

Also, for those who aren't familiar with our labs program, some initial detail is in those meeting notes.

/cc @jonleung

### PR DESCRIPTION
**Pull request by zachlatta**
This closes #30.

Let's hold off on merging this until we have a chance to make sure everyone is okay with our current pipeline.

### CODE REVIEW

**Comment by zachlatta** [comment]
Alright, @jonleung just commented on #30 saying he added the remaining leaders.

@hellyeah can you review/merge this when you have the opportunity?

**Comment by hellyeah** [comment]
Should we close this. We have 25 which is a solid number but I was still thinking I may push a little more on widening the funnel. Amy's posting in NCWIT.

**Comment by zachlatta** [comment]
I'd move for closing this for now. I think the number we're moving forward with is enough for now and we can always add more people later. That okay @hellyeah?

**Comment by zachlatta** [comment]
Whoops, I meant merging this PR. Thoughts on merging this @hellyeah?

**Comment by hellyeah** [comment]
Let's close it. I worry if we try to add more people we won't get labs started before bm.

**Pull request merged**
