### PR TITLE
Feedback guidelines

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@Bogidon @j1lin0101: It seems  like both your clubs have been receiving feedback. Would you like to try some of these tips at your next meeting to bolster the amount of feedback you get?

**Comment by MaxWofford** [comment]
@ssun098 @saescapa: Here's some tips back from when we were running Hack Camp _#funtimes_. Would you like to try them out at your next meeting?

**Comment by MaxWofford** [comment]
@hellyeah Assigning you just for now. Would you please hold off on merging until we hear from some club leaders?

**Comment by MaxWofford** [comment]
@hackedu/core Might as well bring everyone into this. Thoughts so far?

**Comment by MaxWofford** [comment]
@hellyeah I take back what I said previously. This should be merged if it looks ready. Club leaders can comment on the file when it is in master and a new PR can be submitted to add all the touch-ups needed.

**Comment by MaxWofford** [comment]
Because @hellyeah is busy this week, reassigning to @paked

**Comment by paked** [comment]
Thanks @MaxWofford

**Pull request merged**
