### PR TITLE
Remove meeting notes from repo

### PR DESCRIPTION
**Pull request by MaxWofford**
These notes are moved to hackedu/meta in hackedu/meta#281

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta 
```
➜  hackedu git:(migrate-meetings-to-hackedu-repo) g pull --rebase https://github.com/hackedu/hackedu.git master
From https://github.com/hackedu/hackedu
 * branch            master     -> FETCH_HEAD
Current branch migrate-meetings-to-hackedu-repo is up to date.

➜  hackedu git:(migrate-meetings-to-hackedu-repo) git push https://github.com/maxwofford/hackedu
Everything up-to-date
```

**Comment by MaxWofford** [comment]
@zachlatta I derped. Should be good to go!

**Comment by MaxWofford** [comment]
Wait no

**Comment by zachlatta** [comment]
Have you pushed yet? Tests seem to be failing.

**Comment by MaxWofford** [comment]
@zachlatta We're [good to go](https://soundcloud.com/friendjonathanleung/good-to-bueno)

**Comment by MaxWofford** [comment]
This depends on hackedu/meta#281

**Comment by MaxWofford** [comment]
@zachlatta updated!

**Pull request merged**
