### PR TITLE
License repo under the MIT and CC BY-SA licenses

### LINKED ISSUE #260: Add an open source license
Currently this is under full default copyright. 

Creative Commons is probably the most applicable.

### PR DESCRIPTION
**Pull request by zachlatta**
Closes #260.

/cc @paked @MaxWofford @TheThirdOne @ad510

### CODE REVIEW

**Comment by ZucchiniZe** [comment]
Awesome, finally!

**Comment by zachlatta** [comment]
Yeah! I'm so sorry for taking so long with this.

**Comment by paked** [comment]
:+1:

**Comment by TheThirdOne** [comment]
:+1:

**Pull request merged**
