### PR TITLE
San Leandro Case Study 10/22/15

### PR DESCRIPTION
**Pull request by xeonjake**

### CODE REVIEW

**Comment by xeonjake** [comment]
oh no, problem, I only wanted to commit san leadnro 10/22/15 case study 51bb95f

**Comment by MaxWofford** [comment]
@paked Thanks for taking this!

**Comment by paked** [comment]
@MaxWofford I'm still wrestling with it lol.

**Comment by paked** [comment]
Bit of a cray git hell situation

**Comment by MaxWofford** [comment]
@paked Feel free to ask questions. I'm happy to hop into a partytime at maxwofford.com

**Comment by xeonjake** [comment]
@paked will it be easier if I refork the repo and submit a new/clean one?

**Comment by xeonjake** [comment]
I rebased it to #425 and included my upcomming plan for meeting also, should be alot cleaner :wink:

**Comment by MaxWofford** [comment]
@xeonjake Thanks for including the upcoming meeting!

**Comment by MaxWofford** [comment]
Closed by #427

**Pull request closed without merging**
