### PR TITLE
Create fifth meeting recap.md

### PR DESCRIPTION
**Pull request by j1lin0101**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@j1lin0101 Thanks for the contribution!



@jonleung Assigning you because hackedu/meta#245

**Comment by jonleung** [comment]
@j1lin0101, just a couple notes that you might consider for the future:

- name the branch name something more readable. The current branch name is `patch-5` consider naming it `add-5th-meeting-recap

**Comment by jonleung** [comment]
This will be closed when #433 is merged in

**Comment by jonleung** [comment]
This is closed by #435

**Pull request closed without merging**
