### PR TITLE
Recap 3 + two workshops

### PR DESCRIPTION
**Pull request by Bogidon**
Ok, so I realize this is probably a very bad way to do a pull request. I didn't do a rebase and there are 50 commits in this pull request D: 

I'll work on my form, sorry.

### CODE REVIEW

**Comment by MaxWofford** [comment]
@Bogidon Awesome! Thanks for submitting the PR!

What we want to do now to get all those commits from master onto your own is `git rebase -i master`.

**Comment by Bogidon** [comment]
@MaxWofford, yeah I've been syncing via `git pull`. I spent some time with @zachlatta yesterday trying to get my repo properly set up with `rebase`. Unfortunately I had to leave before we were done.

**Comment by zachlatta** [comment]
Squashed and cherry picked into master in edc6ab83b89bba4d72b42197b945cb7be94a3f6f. Awesome contribution.

**Comment by paked** [comment]
@zachlatta, I can't see these in master?

**Comment by MaxWofford** [comment]
@paked Check out https://github.com/hackedu/hackedu/commit/edc6ab83b89bba4d72b42197b945cb7be94a3f6f

screenshot from 2015-09-27 11 35 58

**Pull request closed without merging**
