### PR TITLE
Mention of "student" -> "club member"

### PR DESCRIPTION
**Pull request by zachlatta**
This PR changes mentions of "student" to "club member" everywhere except for meeting notes.

Thanks to @klipspringr for the heads up.

### CODE REVIEW

**Comment by MaxWofford** [comment]
:+1: this. @zachlatta Would you please rebase master ontop of this?

What are your thoughts on changing club member to hacker?

**Comment by zachlatta** [comment]
I like the idea of calling them hackers everywhere, but I feel like it's worth explicitly saying club member here in case someone's not familiar with our terminology (like @klipspringr, who was trying out one of our workshops for a thing she's teaching in socal).

**Comment by zachlatta** [comment]
Rebasing now!

**Comment by MaxWofford** [comment]
Moved to https://github.com/hackedu/hackedu/pull/403

**Comment by zachlatta** [comment]
Kill steal.

**Comment by paked** [comment]
@zachlatta fraud

**Pull request closed without merging**
