### PR TITLE
Fixed grammar

### PR DESCRIPTION
**Pull request by ssun098**
@jonleung

### CODE REVIEW

**Comment by jonleung** [comment]
Thanks for this @ssun098!

**Comment by MaxWofford** [comment]
@jonleung It might be good to squash and reword grammar PRs like this in the future. Would make viewing historyr

**Comment by ssun098** [comment]
@MaxWofford we were under time constraint so we didn't really have time to squash

**Comment by zachlatta** [comment]
@MaxWofford: did we ever get grammar guidelines for commits into
CONTRIBUTING.md?

If not, it's our fault for not having the guidelines set @ssun098
<https://github.com/ssun098>. However, things should not be merged into
master unless they follow all guidelines, regardless of time constraints.
This is to maintain consistency in the codebase and to not set the wrong
precedents.

On Sunday, September 20, 2015, Selynna Sun <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @MaxWofford <https://github.com/MaxWofford> we were under time constraint
> so we didn't really have time to squash
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/202#issuecomment-141833703>.
>


-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by ssun098** [comment]
Yeah @zachlatta sorry about that, @jonleung gave me the ok to merge because our workshop was starting at mhacks

**Comment by jonleung** [comment]
@zachlatta I take full responsibility for @ssun098's merge (I told her we should do it) and made the call that was fine because the changes were not going into master.

**Comment by zachlatta** [comment]
Ah, gotcha. That's my bad then.

On mobile it didn't say that it was merging into your branch and not master.

On Sun, Sep 20, 2015 at 6:02 PM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> I take full responsibility for
> @ssun098 <https://github.com/ssun098>'s merge (I told her we should do
> it) and made the call that was fine because the changes were not going into
> master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/pull/202#issuecomment-141851931>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Pull request merged**
